name: news_app
description: A News Aggregator App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.4.0
  intl: ^0.18.0
  shared_preferences: ^2.0.18
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.1.10
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/